export {default as Home} from './Home/home'
export {Register, Login} from './Auth'
export {default as Contact} from './Contact/contact'
export {Jobs, JobDetails, Apply} from './Jobs'
export {UpdateProfile, Resume} from './User'
export {PostJob} from './Employer'
export {CandidateDashboard, EmployerDashboard} from './Dashboard'